<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Profile>ReTFO</Profile>
    <!-- R2ModMan profile name to build to -->
    <ProjectName>$(MSBuildProjectName.Replace(" ", "_"))</ProjectName>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <BepInEx>$(AppData)\r2modmanPlus-local\GTFO\profiles\$(Profile)\BepInEx</BepInEx>
    <BuildDirectory>$(BepInEx)\plugins\$(ProjectName)\</BuildDirectory>
    <OutputPath>$(BuildDirectory)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <RootNamespace>ReTFO.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <ContentDestFiles Include="$(OutputPath)\**" />
      <AssetDestFiles Include="$(BepInEx)\Assets\$(ProjectName)\**" />
    </ItemGroup>
    <Delete Files="@(ContentDestFiles)" />
    <Delete Files="@(AssetDestFiles)" />
  </Target>
  <Target Name="PostBuild" BeforeTargets="PostBuildEvent">
    <ItemGroup>
      <ContentFiles Include="Content\**" />
      <AssetFiles Include="Assets\**" />
    </ItemGroup>
    <Delete Files="$(OutputPath)$(AssemblyName).deps.json" />
    <Copy SourceFiles="@(ContentFiles)" DestinationFolder="$(OutputPath)\" />
    <Copy SourceFiles="@(AssetFiles)" DestinationFolder="$(BepInEx)\Assets\$(ProjectName)\" />
  </Target>
  <ItemGroup>
    <Reference Include="$(BepInEx)\core\0Harmony.dll" Private="false" />
    <Reference Include="$(BepInEx)\core\BepInEx.Core.dll" Private="false" />
    <Reference Include="$(BepInEx)\core\BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="$(BepInEx)\core\Il2CppInterop.Common.dll" Private="false" />
    <Reference Include="$(BepInEx)\core\Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Addons-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\AssetPrefabs-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Assets-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\BlendEnv.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\BlendHS.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\CellSound-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\CommandSystem.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\DevConsoleCommands-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\DevConsoloe-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Dissonance-integrations-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\DissonanceVoip.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\DropServerSDK-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\ExcludeInBuild-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\FluffyUnderware.DevTools.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\FPSRenderer.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\GameData-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\GlobalFramework-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\GUIX-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppMono.Security.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2Cppmscorlib.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Configuration.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Core.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Data.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Diagnostics.StackTrace.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Globalization.Extensions.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.IO.Compression.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Net.Http.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Numerics.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Runtime.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Runtime.Serialization.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Xml.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Il2CppSystem.Xml.Linq.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\LibTessDotNet.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\LogUtils.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Modules-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\NativeHeap.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Notification-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\PlayFab-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Plugins-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Prototype.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Prototypes_ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Resources-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\RootMotion-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Scenes-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Shards-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\SNet_ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\StandardAssets-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\SteamDataAttribution-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\SteamWorks_ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\ToolBuddy.Curvy.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\ToolBuddy.Curvy.Examples.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.Analytics.DataPrivacy.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.Burst.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.Burst.Unsafe.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.Collections.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.Mathematics.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.Postprocessing.Runtime.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Unity.TextMeshPro.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.AccessibilityModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.AIModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.AndroidJNIModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.AnimationModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ARModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.AssetBundleModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.AudioModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ClothModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ClusterInputModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ClusterRendererModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.CoreModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.CrashReportingModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.DirectorModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.DSPGraphModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.GameCenterModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.GridModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.HotReloadModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ImageConversionModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.IMGUIModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.InputLegacyModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.InputModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.JSONSerializeModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.LocalizationModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ParticleSystemModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.PerformanceReportingModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.Physics2DModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.PhysicsModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ProfilerModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.ScreenCaptureModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.SharedInternalsModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.SpriteMaskModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.SpriteShapeModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.StreamingModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.SubstanceModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.SubsystemsModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.TerrainModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.TerrainPhysicsModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.TextCoreModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.TextRenderingModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.TilemapModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.TLSModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UI.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UIElementsModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UIModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UmbraModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UNETModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityAnalyticsModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityConnectModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityTestProtocolModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityWebRequestAssetBundleModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityWebRequestAudioModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityWebRequestModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityWebRequestTextureModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.UnityWebRequestWWWModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.VehiclesModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.VFXModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.VideoModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.VRModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.WindModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityEngine.XRModule.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\UnityFileDebug-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Utils-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Windows-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="C:\Users\rydan\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\ReTFO\BepInEx\interop\Wwise-ASM.dll">
      <Private>false</Private>
    </Reference>
    <Reference Remove="$(BepInEx)\interop\netstandard.dll" />
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>